services:
  db:
    image: postgres:12.5-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
