version: '3.4'

services:
  db:
    image: postgres:12.5-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    ports:
      - "8081:8081"
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432

volumes:
  dbdata:
