services:
  db:
    image: postgres:12.5-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    volumes:
      - dbdata:/var/lib/postgresql/data

  server:
    image: haskell:8.10.7
    ports:
      - "8081:8081"
    command: cabal run
    build: .
    working_dir: /events
    volumes:
      - .:/events
    depends_on:
      - db

volumes:
  dbdata:
